### ISSUE TITLE
Eliminating initialization overhead on snopt

### ISSUE THREAD

**Issue by A-I-Ivanov** [ethz-adrl/ifopt#30]
I am solving a series of near optimal solutions (i.e. the problem is identical except the initial condition and the initial trajectory guess). I notice that ever time I use the ::Solve(*nlp) function using the snopt76 adapter, SNOPT re-initializes (i.e. checks how many derivatives were defined etc.). Is there a way to simply call "solve" again once the initial conditions have been changed without this initialization?

**Comment by awinkler** [comment]
No, currently this is not implemented. One option I could think of, if this initialization is so costly, is to add an `InitWithNewInitialConditions()` function that calls only these lines:
https://github.com/ethz-adrl/ifopt/blob/77d49148f079709c02658b22b7042a266adeb406/ifopt_snopt/src/snopt_adapter.cc#L82

Then you can the normal `Init()` once and after that this added function. that only updates the starting values.

However, I'm surprised this initialization is so costly. You could also turn of the derivative checking by setting the appropriate option (from [snopt user guide]):(http://web.stanford.edu/group/SOL/guides/sndoc7.pdf)
![selection_006](https://user-images.githubusercontent.com/4179579/43355064-64a05366-9256-11e8-8e5e-afe079b8f1a9.png)

Also make your compilling in release mode (`cmake .. -DCMAKE_BUILD_TYPE=Release`) if you haven't done so, this should make the largest difference.
