### ISSUE TITLE
Problems that contain no constraints segfault

### ISSUE THREAD

**Issue by wxmerkt** [ethz-adrl/ifopt#34]
Hi Alexander,
Thank you very much for providing this great wrapper! I am in the process of integrating it into our motion planning framework (in order to use Ipopt) and came across the following segmentation fault:

- If an NLP contains only a cost term, no constraint terms: it segfaults.
- If a 0-dimensional constraint is added: no segfault.

Best wishes,
Wolfgang

**Comment by awinkler** [comment]
Thanks for pointing this out :+1: . Somewhere the code is probably trying to access the first element of an empty constraint-set vector. I'll look into it asap. If you have time, you could also you figure out where and propose a PR fix :)

**Comment by wxmerkt** [comment]
The somewhere is the `GetJacobian()` call (`components_.first()`)
