### ISSUE TITLE
History related to the creation versus using existing Optmization Interface Libraries?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ethz-adrl/ifopt#36]
Hello,

I have been integrating [TrajOpt](https://github.com/ros-industrial-consortium/trajopt_ros/issues/67) into ROS which came with its own optimization interface library and I am looking at replacing it with one that is currently available like IFOPT. I have been researching and there are several of them available like COIN-OR, CasADI, etc.. I am interested in using this package as it replacement and I am interested to learn how this compares to others. I have no familiarity with any of the packages at the moment, but I assumed you might and any information would be helpful? 

Thank you

**Comment by awinkler** [comment]
Hi Levi!

Yes, there are a few interfaces out there, but i have only briefly looked into them. IFOPTs focus is on making the problem formulation (constraint, jacobian, index management) *easy* (see this [picture](http://docs.ros.org/api/ifopt/html/group__ProblemFormulation.html), which shows the core feature of "sets") and *efficient* by building everything on Eigen. It's 2k lines that have no dependencies except Eigen and IFOPT (both installable with `sudo apt-get...`). So its a low dependency, minimum implementation that can be installed hassle free.

Casadi on the other hand will have a bunch of additional features, like AD and other handy things, so you just have to see what you need. COIN-OR is pure IPOPT as far as i know, I don't know of any interface on top of it.

I'd recommend to [install](https://github.com/ethz-adrl/ifopt#install) and run this [example.cc](https://github.com/ethz-adrl/ifopt/blob/master/ifopt_core/test/ifopt/test_vars_constr_cost.h) which should give you a good feeling how problems are formulated with IFOPT and then do the same for the other interfaces to compare. 

Hope this helps :)
Cheers
Alex
