### ISSUE TITLE
How to compile other linear solver except mumps

### ISSUE THREAD

**Issue by csyzzkdcz** [ethz-adrl/ifopt#37]
Hi folks, 

I just wonder whether and how I can compile other linear solvers except for MUMPS?

**Comment by awinkler** [comment]
You can set other solvers as shown here:
https://github.com/ethz-adrl/ifopt/blob/8cc91688935867a67daeb39a8ff9ddb3f9750668/ifopt_ipopt/test/ex_test_ipopt.cc#L46
