### ISSUE TITLE
not compatible with Snopt 7.6 (Latest version)

### ISSUE THREAD

**Issue by depardo** [ethz-adrl/ifopt#4]
The C++ interface of SNOPT has changed from 7.5.x to 7.6 so users buying the license since January 2017 cannot use the current IFopt interface. Should we create an alternative branch to support both interfaces?

**Comment by awinkler** [comment]
Thanks for letting me know. I would not create a new branch, but treat the new SNOPT interface as a 3rd separate solver and therefore implement a new class "SnoptAdapter76" (`snopt_adapter_76.h`  and `snopt_adapter_76.cc` ). The only additional element that must be adapted is then the CMakeLists.txt that must know which SNOPT version to link against which SNOPT adapter class. 

This then allows the user after defining the entire problem to decide whether to solve it with IPOPT, SNOPT or the new version of SNOPT:
``IpoptAdapter::Solve(nlp); // or SnoptAdapter::Solve(nlp) or SnoptAdapter76::Solve(nlp) ``
