### ISSUE TITLE
New tagged ROS release that includes newest commits

### ISSUE THREAD

**Issue by archielee** [ethz-adrl/ifopt#43]
Hi,

I found the new return code change introduced in #40 useful and our code base is currently using the master branch of this repository. However, it would be helpful if this was released through ROS. Would it be possible for you to create a new tagged version for ROS Kinetic that includes the above commit please?

Thank you very much!

**Comment by awinkler** [comment]
Yes, version 2.0.7. was just released and should be part of the binaries in the next days.
