### ISSUE TITLE
fatal error :coin/InIpoptApplication.hpp :no such file or directory 

### ISSUE THREAD

**Issue by JiangxinkeTao** [ethz-adrl/ifopt#56]
When I use the "catkin_make " to install the ifopt in my workspace ,I use the IPOPT example "hs071_cpp"(https://github.com/coin-or/Ipopt/tree/master/examples/hs071_cpp) to compile ,it occur the problem that fatal error :coin/InIpoptApplication.hpp :no such file or directory ;Can you solve my problem ?THANK YOU VERY MUCH!

**Comment by awinkler** [comment]
Hi! you can use ifopt with `mumps` for it to work out of the box, as this is preinstalled with the ubuntu install (`sudo apt install coinor-libipopt-dev`). For that follow the instructions on the README.

The example you posted is pure IPOPT, so not relevant or maintained through this project IFOPT (the wrapper).
