### ISSUE TITLE
ROS 2 Foxy Release?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ethz-adrl/ifopt#66]
I noticed that this package has releases on most of the ROS 1 distros, but did not see anything on the ROS 2 distros. Are there plans to release this on ROS 2 Foxy?

**Comment by awinkler** [comment]
Wasn't on my radar, but will think about it if people would find this useful. Will ROS1 be deprecated at some point?

**Comment by Levi-Armstrong** [comment]
I believe Noetic is the last release of ROS 1. We currently use IFOPT on ROS 2 just building from source and the release process is very similar.

**Comment by vatanaksoytezer** [comment]
@awinkler we would also appreciate a Foxy release, this would mean one less source build for all repos using ifopt.

**Comment by DLu** [comment]
@awinkler +1 for Foxy release. Happy to help as needed

**Comment by awinkler** [comment]
Sorry for being unresponsive, I'm a bit swamped right now. But happy to give you write access to the relevant repos to create the required ROS releases, if that's something you'd be willing to do.

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/31177

**Comment by awinkler** [comment]
awesome, thanks @DLu!

**Comment by Levi-Armstrong** [comment]
@DLu Did you also do an updated noetic release?

**Comment by DLu** [comment]
Sorry, I was too slow to get to this. Thanks for releasing it @Levi-Armstrong
