### ISSUE TITLE
Request release of latest on ROS Noetic?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ethz-adrl/ifopt#69]
We are currently leveraging some of the recent change and wanted to see if you would be willing to release the latest state of the repo?

**Comment by Levi-Armstrong** [comment]
@awinkler If you give me access to the the release repositories I will also help out with creating release starting with updating the noetic release.

**Comment by awinkler** [comment]
that would be amazing, thanks so much! added you to all as maintainer.

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/31238
