### ISSUE TITLE
errors with Snopt 7.7

### ISSUE THREAD

**Issue by basitimran37** [ethz-adrl/ifopt#75]
```make test``` passes for both snopt and ipopt but when I use ```SnoptSolver solver``` and ```solver.Solve(nlp)``` in my code instead of ```IpoptSolver```, it throws the following errors:

undefined reference to 'vtable for ifopt::SnoptSolver'
undefined reference to 'ifopt::SnoptSolver::Solve(ifopt::Problem&)

I have already followed the suggestions in #31 to make SNOPT work.

**Comment by basitimran37** [comment]
This was just a missing reference to snopt in CmakeLists.txt of my project. Resolved!

**Comment by shbang91** [comment]
Hello, 
I am using Snopt 7.7 and build the ifopt_snopt successfully, but still `make test` failed. Could you share what modification you made?

I've already followed [https://github.com/ethz-adrl/ifopt/issues/31](url).

Thank you.
