### ISSUE TITLE
Get Iterations History

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [ethz-adrl/ifopt#77]
First, I would like to congratulate the contributors of this project. It is a great work.

I would like to ask if there is a canonical way to get the value of the optimization variables for the iterations along the optimization process.
I see that the class `ifopt::Problem`  has a member `x_prev` which I think it contains the data i desire. But this member is private.
My questions are:

1. Contains `x_prev`  the history of the iterations?
2. Is there a way to get its value?

I think that a const method `const std::vector<VectorXd> &GetIterations() const { return x_prev; };` will be usefull. It this solves the problem I can do a pull request.

**Comment by Levi-Armstrong** [comment]
I think this is reasonable. If you create a PR I will review it.
